WIP: add nifti_image_write_status
NIFTI-Imaging/nifti_clib pull request #147
Opened 2022-06-06 20:20 UTC by afni-rickr

add NIFTI-1 and -2 versions of nifti_image_write_status

2022-06-07 16:37 UTC, gdevenyi commented
Just a thought, have you considered converting `nifti_image_write` to a thin wrapper which calls `nifti_image_write_status` and discards the return bits? This could reduce code duplication and ensure a unified path for code testing etc.

2022-06-07 17:07 UTC, afni-rickr commented
@gdevenyi Yes, there are many such bits to possibly do.  Currently, nifti_image_write does call _status, except that it goes through 2 intermediate layers first.  We could cut out those layers, though it is weighed against modifying functions that work as they are.  But if you think _write should call _status, I will make that change.  I will duplicate most of this in the NIFTI-1 library, too.  Thanks.

2022-06-07 17:42 UTC, gdevenyi commented
I think for consistency/uniformity it makes sense for `nifti_image_write` and `nifti_image_write_status` to take the same pathways through the code wherever possible.

My only concern is that based on your description, changing `nifti_image_write` to wrap `nifti_image_write_status` is a big-ish change to the existing codeflow, as they're implemented differently? I can see either side of this discussion winning out, perhaps it depends on what the next version # of the release would be :)

2022-06-07 19:09 UTC, afni-rickr commented
The addition of _engine is already modifying the code for most of the image_write functions, including nifti_image_write, so this is already a somewhat impactful change.  Since nifti_image_write is already calling the engine (indirectly), it would make sense to just be direct about it.
I am thinking to make a similar nifti_image_write_bricks_status function, too, esp. since write_bricks is already relying on _engine.
So the _engine function is the real change (for NIFTI-1 and -2), but it will lead to lots of little changes, including in the examples.

2022-06-15 17:01 UTC, hjmjohnson commented on nifti2/nifti_tool.c
> +         fprintf(stderr,"** failed to write image %s\n",
Should this be protected by "if( g_opts.debug > 1 )"?

2022-06-15 17:01 UTC, hjmjohnson commented on nifti2/nifti_tool.c
> +         fprintf(stderr,"** failed to write image %s\n", nim->fname);
Should this be protected by "if( g_opts.debug > 1 )"?

2022-06-15 17:01 UTC, hjmjohnson commented on nifti2/nifti_tool.c
> +         fprintf(stderr,"** failed to write image %s\n", nim->fname);
Should this be protected by "if( g_opts.debug > 1 )"?

2022-06-15 17:01 UTC, hjmjohnson commented on nifti2/nifti_tool.c
> +            fprintf(stderr,"** failed to write image %s\n", nim->fname);
Should this be protected by "if( g_opts.debug > 1 )"?

2022-06-15 17:02 UTC, hjmjohnson commented on nifti2/nifti_tool.c
> +            fprintf(stderr,"** failed to write image %s\n", nim->fname);
Should this be protected by "if( g_opts.debug > 1 )"?

2022-06-15 17:02 UTC, hjmjohnson commented on nifti2/nifti_tool.c
> +         fprintf(stderr,"** failed to write image %s\n", nim->fname);
Should this be protected by "if( g_opts.debug > 1 )"?

2022-06-15 17:02 UTC, hjmjohnson commented on niftilib/nifti1_io.c
>          fprintf(stderr,"** NIfTI: cannot swap in %d byte blocks\n", siz);
Should this be protected by "if( g_opts.debug > 1 )"?

2022-06-15 17:03 UTC, hjmjohnson requested changes
Overall looks good.  I am concerned about printing to stderr unconditionally in some cases.

2022-06-15 17:10 UTC, afni-rickr commented
For the most part, serious errors have always been printed to stderr unconditionally.
There are some cases of `if( g_opts.debug > 0 )`, but not so many.  Also, the _engine, as with the old hdr_img2 code will generally print the reason for failure.  Those could be wrapped in a test for debug > 0 (probably not 1), but that would be a change.

2022-06-15 17:15 UTC, hjmjohnson commented
@afni-rickr I am OK with not changing historical behavior in the PR.

I recommend that a future PR consider not writing to terminal stderr from library functions.  Where should those messages be displayed for a GUI application?

2022-06-15 17:22 UTC, afni-rickr commented
@hjmjohnson sure, a future PR preventing default stderr writing from the library seems reasonable.  For a GUI, are those messages simply not seen?  If that is what happens, such a PR would not affect them.  We can ponder it.

2022-06-15 17:32 UTC, afni-rickr commented
@hjmjohnson I am going to make a quick parallel update for nifti_image_write_bricks (which is already calling _engine, eventually).  Would you like a test added for such a failure case?  I have done local testing using a read-only output directory.

2022-06-15 17:35 UTC, hjmjohnson commented
@afni-rickr I think that test may be hard to write.  I'll be satisfied with historical testing that did not test the error status.

Thank you for you assistance with making these changes.

2022-06-15 19:58 UTC, afni-rickr commented
@hjmjohnson Okay, I think this is ready.  Would you like a last peek at the recent commits?  Please feel free to merge if you are happy (or at least moderately satisfied :).

2022-06-16 16:05 UTC, hjmjohnson approved these changes

2022-06-16 16:06 UTC, merged